---
title: "Discon Naming and Visual Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE) #no code, no warning printed
library(knitr)
library(tidyverse)
library(ggplot2)
library(jsonlite)
library(tidyr)
library(stringr)
library(dplyr)
library(ggthemes)
library(langcog)
```

#Pilot 1 data
```{r data preprocessing}
# Data pre-processing

files <- dir("../../adult_600_raw_data/production-results/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../adult_600_raw_data/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data_control <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = factor(distribution, levels = c("c(6, 0, 0)")))

data_ip <- data_control %>%
  filter(phase == 'training') %>%
  group_by(workerIp) %>%
  summarise(correct = mean(correct_item))

data_control <- data_control %>% 
  distinct(workerIp, trial, slide, .keep_all = TRUE)

files <- dir("../../adult_600_visual/production-results/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../adult_600_visual/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data_visual <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = factor(distribution, levels = c("c(6, 0, 0)")))

data_ip <- data_visual %>%
  filter(phase == 'training') %>%
  group_by(workerIp) %>%
  summarise(correct = mean(correct_item))

data_visual <- data_visual %>% 
  distinct(workerIp, trial, slide, .keep_all = TRUE)

files <- dir("../../adult_600_name/production-results/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../adult_600_name/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data_name <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = factor(distribution, levels = c("c(6, 0, 0)")))

data_ip <- data_name %>%
  filter(phase == 'training') %>%
  group_by(workerIp) %>%
  summarise(correct = mean(correct_item))

data_name <- data_name %>% 
  distinct(workerIp, trial, slide, .keep_all = TRUE)
      
data <- bind_rows(data_control, data_name, data_visual)
```

```{r}
data_ip <- data %>%
  filter(phase == 'training') %>%
  group_by(workerIp) %>%
  summarise(correct = mean(correct_item))
```

```{r sanity checks}
data %>%
  filter(phase == 'training') %>%
  group_by(workerid) %>%
  summarise(correct = mean(correct_item))

drop <- data %>%
  filter(phase == 'training') %>%
  group_by(workerid) %>%
  summarise(correct = mean(correct_item)) %>%
  filter(correct < 0.83) %>%
  pull(workerid)

data <- data %>%
  filter(!workerid %in% drop)
```
```{r}

sample_size <- data %>%
  distinct(workerid, .keep_all = TRUE)

sample_size %>%
 group_by(experiment) %>%
 summarise(n = n())
```


```{r plot1}
plot1 <- data %>%
  filter(phase == 'test') %>%
  group_by(distribution, workerid, experiment) %>%
  summarise(correct = mean(correct_target1),
            correct2 = mean(correct_target2),
            correct3 = mean(correct_target3)) %>%
  gather(item, prop_correct, -distribution, -workerid, -experiment) %>%
  group_by(distribution, item, experiment) %>%
  multi_boot_standard(col = "prop_correct")


ggplot(plot1,
       aes(x = item, y=mean, fill=item)) +
  geom_bar(stat='identity') +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) +
  scale_fill_solarized(name = "Chosen item",
                       breaks = c("correct", "correct2", "correct3"),
                       labels = c("most frequent", "second most frequent", "least frequent"))+
  facet_grid(~experiment, 
             labeller = as_labeller(c(distribution_adults = "Control", distribution_adults_name = "Names", distribution_adults_visual = "Visual"))) +
  geom_hline(yintercept = 1/3, lty=2) +
  ylim(0, 1) +
  theme_few() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  labs(x="", y= "proportion chosen")

```