---
title: "Discon recency analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(jsonlite)
library(tidyr)
library(stringr)
library(dplyr)
library(ggthemes)
library(langcog)
```

#Recency data ("another one")
```{r}
files <- dir("../../recency_raw_data/production-results")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../recency_raw_data/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data_recency_another <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = factor(distribution, levels = c("c(5, 1, 0)", "c(2, 2, 2)")))

data_ip <- data_recency_another %>%
  filter(phase == 'training') %>%
  group_by(workerIp) %>%
  summarise(correct = mean(correct_item))

data_recency_another <- data_recency_another %>% 
  distinct(workerIp, trial, slide, .keep_all = TRUE)
```

#Recency data ("Here's the last one.")
```{r}
files <- dir("../../recency_last_raw_data/production-results")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../recency_last_raw_data/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data_recency_last <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = factor(distribution, levels = c("c(5, 1, 0)", "c(2, 2, 2)")))

data_ip <- data_recency_last %>%
  filter(phase == 'training') %>%
  group_by(workerIp) %>%
  summarise(correct = mean(correct_item))

data_recency_last <- data_recency_last %>% 
  distinct(workerIp, trial, slide, .keep_all = TRUE)
```

#Recency data ("Look at that.")
```{r}
files <- dir("../../recency_look_raw_data/production-results")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../recency_look_raw_data/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data_recency_look <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = factor(distribution, levels = c("c(5, 1, 0)", "c(2, 2, 2)")))

data_ip <- data_recency_look %>%
  filter(phase == 'training') %>%
  group_by(workerIp) %>%
  summarise(correct = mean(correct_item))

data_recency_look <- data_recency_look %>% 
  distinct(workerIp, trial, slide, .keep_all = TRUE)
```

```{r}
data <- bind_rows(data_recency_another, data_recency_last, data_recency_look)

#check if workerIp is repeating
data_ip <- data %>%
  filter(phase == 'training') %>%
  group_by(workerIp) %>%
  summarise(correct = mean(correct_item))
```

```{r sanity checks}
data %>%
  filter(phase == 'training') %>%
  group_by(workerid) %>%
  summarise(correct = mean(correct_item))

drop <- data %>%
  filter(phase == 'training') %>%
  group_by(workerid) %>%
  summarise(correct = mean(correct_item)) %>%
  filter(correct < 0.83) %>%
  pull(workerid)

data <- data %>%
  filter(!workerid %in% drop)
```

# Do proportion of choices match the frequency in the distribution?
```{r plot1}
plot1 <- data %>%
  filter(phase == 'test', distribution == "c(5, 1, 0)") %>%
  group_by(distribution, workerid, experiment) %>%
  summarise(correct = mean(correct_target1),
            correct2 = mean(correct_target2),
            correct3 = mean(correct_target3)) %>%
  gather(item, prop_correct, -distribution, -workerid, -experiment) %>%
  group_by(distribution, item, experiment) %>%
  multi_boot_standard(col = "prop_correct")


ggplot(plot1,
       aes(x = item, y=mean, fill=item)) +
  geom_bar(stat='identity') +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) +
  scale_fill_solarized(name = "Chosen item",
                       breaks = c("correct", "correct2", "correct3"),
                       labels = c("most frequent", "second most frequent", "least frequent"))+
  facet_grid(~experiment, 
             labeller = as_labeller(c(`c(5, 1, 0)` = "Distribution\n(5-1-0)", `c(2, 2, 2)` = "Distribution\n(2-2-2)", recency = "Here's another one.", recency_last = "Here's the last one.", recency_look = "Look at that."))) +
  geom_hline(yintercept = 1/3, lty=2) +
  ylim(0, 1) +
  theme_few() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  labs(x="", y= "proportion chosen")
```

# How does the last item seen affect the object chosen in the anaphora case? 
```{r}
plot2 <- data %>%
  filter(phase == "test", distribution != "c(6, 0, 0)") %>%
#  mutate(trackLast = ifelse(lastInputCat == target1, "yes", "no")) %>%
  group_by (distribution, workerid, experiment) %>%
  summarise (lastInput = mean(same_lastInput),
             n = n()) %>%
  group_by(distribution, experiment) %>%
  multi_boot_standard(col = "lastInput")
  
ggplot(plot2,
       aes(x = distribution, y = mean, fill = distribution)) +
  geom_bar(stat='identity') +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) +
  facet_grid(~experiment, 
             labeller = as_labeller(c(recency = "Here's another one.", recency_last = "Here's the last one.", recency_look = "Look at that.")))+ 
  geom_hline(yintercept = 1/3, lty=2) +
  ylim(0, 1) +
  theme_few() +
  labs(x="", y= "proportion chosen same as last item")
```

# Are there 2 strategies in determining what "another one" means?
```{r}
plot3 <- data %>%
  filter(phase == 'test') %>%
  group_by(distribution, workerid, experiment) %>%
  summarise(correct = mean(correct_target1),
            correct2 = mean(correct_target2),
            correct3 = mean(correct_target3)) %>%
  gather(item, prop_correct, -distribution, -workerid, -experiment) %>%
  group_by(distribution, item, experiment) 

plot3a <- plot3 %>%
  multi_boot_standard(col = "prop_correct")

ggplot() +
  geom_jitter(data = plot3, aes(x = item, y = prop_correct, col = item, alpha = .2), width = .3,height = .025)+
  geom_pointrange(data = plot3a, aes(x = item, y = mean, col = item, ymin = ci_lower, ymax = ci_upper),size = .8)+
  facet_grid(experiment~distribution, 
             labeller = as_labeller(c(`c(5, 1, 0)` = "Distribution\n(5-1-0)", `c(2, 2, 2)` = "Distribution\n(2-2-2)", recency = "Here's another one.", recency_last = "Here's the last one.", recency_look = "Look at that.")))+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="Item Chosen", y="Proportion Chosen")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
 # theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))

#No - if 2 strategies: there should be fewer dots in the middle
```