---
title: "DisCon Speaker Change Adult with Preference Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE) #no code, no warning printed
library(knitr)
library(tidyverse)
library(ggplot2)
library(jsonlite)
library(tidyr)
library(stringr)
library(dplyr)
library(ggthemes)
library(langcog)
```

# Data for speaker change with preference framing
```{r data preprocessing}
# Data pre-processing

files <- dir("../../adult_600_speakerchange_preference/production-results/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../adult_600_speakerchange_preference/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = ifelse(distribution == "2:0", "c(2, 1, 0)", distribution),
         distribution = factor(distribution, levels = c("c(6, 0, 0)", "c(4, 2, 0)", "c(2, 2, 2)", "c(3, 0, 0)", "c(1, 1, 1)", "c(2, 1, 0)")))


#write.csv(data, file="../data/01_adult_speakerchange_preference.data.csv")

data <- read_csv(file="../data/01_adult_speakerchange_preference.data.csv")
```

## Cleaning data

Remove participants who perform below cut-off in training and who participated

```{r sanity checks}
drop_train <- data %>%
  filter(phase == 'training') %>%
  group_by(workerid) %>%
  summarise(correct = mean(correct_item)) %>%
  filter(correct < 0.83) %>%
  pull(workerid)

data <- data %>%
  distinct(workerid, trial, slide, .keep_all = TRUE)%>%
  filter(!workerid %in% drop_train)
```
## Sample size

```{r}
data %>%
  filter(phase=="test")%>%
  group_by(speakerChange)%>%
  summarise(N = length(unique(workerid)),
            datapoints = n())

```

# Plotting performance by condition

```{r plot1}
plot3 <- data %>%
  filter(phase == 'test') %>%
  group_by(distribution, workerid, speakerChange) %>%
  summarise(correct = mean(correct_target1)) %>%
  gather(item, prop_correct, -distribution, -workerid, -speakerChange) %>%
  group_by(distribution, item, speakerChange) 

plot3a <- plot3 %>%
  multi_boot_standard(col = "prop_correct")

ggplot() +
  geom_jitter(data = plot3, aes(x = speakerChange, y = prop_correct, col = speakerChange, alpha = .2), width = .3,height = .025)+
  geom_pointrange(data = plot3a, aes(x = speakerChange, y = mean, col = speakerChange, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="Speaker Change", y="Correct Item Chosen")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F) +
  scale_colour_solarized(name = "Speaker Change",
                       breaks = c("change", "same"),
                       labels = c("Different Speaker", "Same Speaker"))


```

# Comparison to chance in each condition

```{r wilcoxon test}
## Wilcoxon tests against chance
library(exactRankTests)

data %>%
  filter(phase == "test") %>%
  group_by(speakerChange, workerid) %>%
  summarise(correct = mean(correct_target1)) %>%
  summarise(correct = list(correct)) %>%
  group_by(speakerChange) %>%
  mutate(mean= mean(unlist(correct)),
         stat = wilcox.exact(unlist(correct), mu = 1/3)$statistic,
         p = wilcox.exact(unlist(correct), mu = 1/3)$p.value) %>%
  select(speakerChange,mean,stat,p) %>%
  knitr::kable(digits = 3)
```

# Model

```{r Bayesian}
library(brms)

model_data <- data%>%
  filter(phase == "test")

#   model

bm1 <- readRDS("../saves/01_adult_speakerchange_model_bm1.rds")

brm(correct_target1 ~ speakerChange +
                      (speakerChange | workerid) + (speakerChange | target1),
                    data = model_data, family = bernoulli(),
          control = list(adapt_delta = 0.95),
          sample_prior = F,
          save_all_pars = TRUE,
          iter = 2000)

saveRDS(bm1, "../saves/01_adult_speakerchange_model_bm1.rds")


```

## Plot model predictors

```{r}
bayesplot::mcmc_areas(as.array(bm1), pars = c("b_Intercept", "b_speakerChangesame"), prob = 0.95)+
  geom_vline(xintercept = 0, lty = 2, col = "black")+
  theme_few()
```

## Model comparison

```{r}
# model comparison
# reduced model

bm2 <- readRDS("../saves/01_adult_speakerchange_model_bm2.rds")

bm2 <- brm(correct_target1 ~ 1 +
                      (speakerChange | workerid) + (speakerChange | target1),
                    data = model_data, family = bernoulli(),
          control = list(adapt_delta = 0.95),
          sample_prior = F,
          save_all_pars = TRUE,
          iter = 2000)

saveRDS(bm2, "../saves/01_adult_speakerchange_model_bm2.rds")

# WAIC scores

child_waic <- brms::WAIC(bm1, bm2, compare = F)

child_weights <- model_weights(bm1, bm2)

# Bayes Factors (slightly variable)
bf_full_null <- bayes_factor(bm1, bm2, log = FALSE, maxiter = 5000)

```
## Model comparison using WAIC and Bayes Factor
```{r}
data_frame(
  model = c("bm1_w_condition","bm2"),
  WAIC = c(child_waic$bm1$estimates[3,1],child_waic$bm2$estimates[3,1]),
  SE = c(child_waic$bm1$estimates[3,2],child_waic$bm2$estimates[3,2]),
  weight = c(child_weights[1],child_weights[2]),
  BF_bm1_bm2 = c(round(bf_full_null$bf,2),"-"))%>%
  kable(digits = 2)
```




