---
title: "DisCon Adult Study 1"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(ggplot2)
library(jsonlite)
library(tidyr)
library(stringr)
library(dplyr)
library(ggthemes)
library(langcog)
```

```{r data preprocessing}
# Data pre-processing
files <- dir("../../adult_raw_data/production-results/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../adult_raw_data/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data_high <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = ifelse(distribution == "2:0", "c(2, 1, 0)", distribution),
         distribution = factor(distribution, levels = c("c(6, 0, 0)", "c(4, 2, 0)", "c(2, 2, 2)", "c(3, 0, 0)", "c(1, 1, 1)", "c(2, 1, 0)")))

files <- dir("../../adult_relative_raw_data/production-results/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../adult_relative_raw_data/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data_low <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = ifelse(distribution == "2:0", "c(2, 1, 0)", distribution),
         distribution = factor(distribution, levels = c("c(6, 0, 0)", "c(4, 2, 0)", "c(2, 2, 2)", "c(3, 0, 0)", "c(1, 1, 1)", "c(2, 1, 0)")))
```

```{r sanity checks, include=FALSE} 
#remove duplicated ips and workers who do not pass the training threshold
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

data_low_ip <- data_low %>% 
  filter(!is.na(workerIp)) %>%
  distinct(workerIp, trial, slide, .keep_all = TRUE)

data_low_no_ip <- data_low %>%
  filter(is.na(workerIp))

data_low <- bind_rows(data_low_ip, data_low_no_ip)

data_high_ip <- data_high %>% 
  filter(!is.na(workerIp)) %>%
  distinct(workerIp, trial, slide, .keep_all = TRUE)

data_high_no_ip <- data_high %>%
  filter(is.na(workerIp))

data_high <- bind_rows(data_high_ip, data_high_no_ip)

data <- bind_rows(data_high, data_low)

data %>%
  filter(phase == 'training') %>%
  group_by(workerid) %>%
  summarise(correct = mean(correct_item))

drop <- data %>%
  filter(phase == 'training') %>%
  group_by(workerid) %>%
  summarise(correct = mean(correct_item)) %>%
  filter(correct < 0.83) %>%
  pull(workerid)

data <- data %>%
  filter(!workerid %in% drop) %>%
  mutate(distribution_prop = ifelse(distribution == "c(6, 0, 0)" | distribution == "c(3, 0, 0)", "1.00-0.00-0.00", ifelse(distribution == "c(4, 2, 0)" | distribution == "c(2, 1, 0)", "0.66-0.33-0.00", "0.33-0.33-0.33")),
         distribution_prop = factor(distribution_prop, levels = c("1.00-0.00-0.00", "0.66-0.33-0.00", "0.33-0.33-0.33")))

sample_size <- data %>%
  distinct(workerid, .keep_all = TRUE)

sample_size %>%
 summarise(n = n()) %>%
 kable()
```

```{r plot1, echo=FALSE}
plot1 <- data %>%
  filter(phase == 'test') %>%
  group_by(distribution_prop, workerid, experiment) %>%
  summarise(correct = mean(correct_target1),
            correct2 = mean(correct_target2),
            correct3 = mean(correct_target3)) %>%
  gather(item, prop_correct, -distribution_prop, -workerid, -experiment) %>%
  group_by (distribution_prop, item, experiment) %>%
  multi_boot_standard(col = "prop_correct")


ggplot(plot1,
       aes(x = item, y=mean, fill=item)) +
  geom_bar(stat='identity') +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) +
  scale_fill_solarized(name = "Chosen item",
                       breaks = c("correct", "correct2", "correct3"),
                       labels = c("most frequent", "second most frequent", "least frequent"))+
  facet_grid(experiment~distribution_prop,
             labeller = as_labeller(c("distribution_adults" = "high", "distribution_adults_relative" = "low", "1.00-0.00-0.00" = "1.00-0.00-0.00", "0.66-0.33-0.00" = "0.66-0.33-0.00", "0.33-0.33-0.33" = "0.33-0.33-0.33"))) +
  geom_hline(yintercept = 1/3, lty=2) +
  ylim(0, 1) +
  theme_few() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  labs(x="", y= "proportion chosen")
```

```{r plot2, echo=FALSE}
plot2 <- data %>%
  filter(phase == "test", distribution != "c(6, 0, 0)", distribution != "c(3, 0, 0)") %>%
  group_by (distribution, workerid) %>%
  summarise (lastInput = mean(same_lastInput),
             n = n()) %>% 
  multi_boot_standard(col = "lastInput")

ggplot(plot2,
       aes(x = distribution, y = mean, fill = distribution)) +
  geom_bar(stat='identity', width = 0.3) +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) +
  scale_fill_solarized(name = "Distribution",
                       breaks = c("c(6, 0, 0)", "c(4, 2, 0)", "c(2, 2, 2)", "c(3, 0, 0)", "c(2, 1, 0)", "c(1, 1, 1)"),
                       labels = c("(6-0-0)", "(4-2-0)", "(2-2-2)", "(3-0-0)", "(2-1-0)", "(1-1-1)"))+
  geom_hline(yintercept = 1/3, lty=2) +
  ylim(0, 1) +
  theme_few() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  labs(x="", y= "proportion chosen same as last item")
```

```{r wilcoxon test}
## Wilcoxon tests against chance
library(exactRankTests)

data %>%
  filter(phase == "test") %>%
  group_by(distribution, workerid) %>%
  summarise(correct = mean(correct_target1)) %>%
  summarise(correct = list(correct)) %>%
  group_by(distribution) %>%
  mutate(mean= mean(unlist(correct)),
         stat = wilcox.exact(unlist(correct), mu = 0.5)$statistic,
         p = wilcox.exact(unlist(correct), mu = 0.5)$p.value) %>%
  select(distribution,mean,stat,p) %>%
  knitr::kable(digits = 3)
```

```{r Bayesian}
library(brms)

data_inf <- data%>%
  filter(phase == "test")

prior1 <- get_prior(correct_target1 ~ distribution_prop * experiment +
                      (distribution_prop | workerid) + (distribution_prop | agent),
                    data = data_inf, family = bernoulli()) 

# registered  model
bm1 <- brm(correct_target1 ~ distribution_prop * experiment +
                      (distribution_prop | workerid) + (distribution_prop | agent),
                    data = data_inf, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          save_all_pars = TRUE,
          prior = prior1,
          iter = 100000)
summary(bm1)

prior2 <- get_prior(correct_target1 ~ distribution_prop +
                      (distribution_prop | workerid) + (distribution_prop | agent),
                    data = data_inf, family = bernoulli()) 

bm2 <- brm(correct_target1 ~ distribution_prop  +
                      (distribution_prop | workerid) + (distribution_prop | agent),
                    data = data_inf, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          save_all_pars = TRUE,
          prior = prior2,
          iter = 100000)
summary(bm2)

bf_full_null <- bayes_factor(bm1, bm2, log = FALSE, maxiter = 5000)

bf_full_null
```

