---
title: "DisCon Adult Study 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(jsonlite)
library(tidyr)
library(stringr)
library(dplyr)
library(ggthemes)
library(langcog)
```

```{r data preprocessing}
# Data pre-processing

files <- dir("../../adult_600_raw_data/production-results/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("../../adult_600_raw_data/production-results/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$answers$data$data) %>%
    mutate(workerid = jd$WorkerId)
  raw_data <- bind_rows(raw_data, id)
}

data <- raw_data %>%
  mutate(distribution = as.character(distribution),
         distribution = ifelse(distribution == "2:0", "c(2, 1, 0)", distribution),
         distribution = factor(distribution, levels = c("c(6, 0, 0)", "c(4, 2, 0)", "c(2, 2, 2)", "c(3, 0, 0)", "c(1, 1, 1)", "c(2, 1, 0)")))

write.csv(data, file="../data/01_study2_adult.data.csv")
data <- read_csv(file="../data/01_study2_adult.data.csv")
```

```{r sanity checks, include=FALSE} 
#remove duplicated ips and workers who do not pass the training threshold
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

data <- data %>% 
  distinct(workerIp, trial, slide, .keep_all = TRUE)

data %>%
  filter(phase == 'training') %>%
  group_by(workerid) %>%
  summarise(correct = mean(correct_item))

drop <- data %>%
  filter(phase == 'training') %>%
  group_by(workerid) %>%
  summarise(correct = mean(correct_item)) %>%
  filter(correct < 0.83) %>%
  pull(workerid)

data <- data %>%
  filter(!workerid %in% drop)

sample_size <- data %>%
  distinct(workerid, .keep_all = TRUE)

sample_size %>%
 summarise(n = n()) %>%
 kable()
```

```{r plot1, echo=FALSE}
plot1 <- data %>%
  filter(phase == 'test') %>%
  group_by(distribution, workerid) %>%
  summarise(correct = mean(correct_target1),
            correct2 = mean(correct_target2),
            correct3 = mean(correct_target3)) %>%
  gather(item, prop_correct, -distribution, -workerid) %>%
  group_by(distribution, item) %>%
  multi_boot_standard(col = "prop_correct")


ggplot(plot1,
       aes(x = item, y=mean, fill=item)) +
  geom_bar(stat='identity') +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper)) +
  scale_fill_solarized(name = "Chosen item",
                       breaks = c("correct", "correct2", "correct3"),
                       labels = c("most frequent", "second most frequent", "least frequent"))+
  facet_grid(~distribution,
             labeller = as_labeller(c(`c(6, 0, 0)` = "Distribution\n(6-0-0)"))) +
  geom_hline(yintercept = 1/3, lty=2) +
  ylim(0, 1) +
  theme_few() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  labs(x="", y= "proportion chosen")
```

#Results across trials
```{r plot2, echo=FALSE}
plot2 <- data %>%
  filter(phase == 'test') %>%
  group_by(distribution, trial, workerid) %>%
  summarise(correct = mean(correct_target1)) %>%
  gather(item, prop_correct, -distribution, -trial, -workerid) %>%
  group_by(distribution, item, trial) %>%
  multi_boot_standard(col = "prop_correct")

ggplot(plot2, 
       aes(x = trial, y = mean, col = item)) +
  geom_line(aes(group = item)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  scale_colour_solarized(name = "Chosen item",
                       breaks = c("correct", "correct2", "correct3"),
                       labels = c("most frequent", "second most frequent", "least frequent"))+ 
  geom_hline(yintercept = 1/3, lty=2)+
  theme_few() +
  labs(x="trial", y= "proportion chosen")
```