---
title: "DisCon Kids Pilot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(jsonlite)
library(tidyr)
library(stringr)
library(dplyr)
library(ggthemes)
library(langcog)

library(lsr)
library(pwr)

```

```{r data}
# data from pilot
data <- read_csv(file="../data/kids_4cat_pilot.data.csv")
```
# Data processing
```{r sanity checks}
data <- data %>% 
  filter(subid != "", subid != "test", subid != "Test")

# check training performance
data %>%
  filter(phase == 'training') %>%
  group_by(subid) %>%
  summarise(correct = mean(correct_item))

# filter out children that don't get known words right
drop <- data %>%
  filter(phase == 'training') %>%
  group_by(subid) %>%
  summarise(correct = mean(correct_item)) %>%
  filter(correct < 0.83) %>%
  pull(subid)

data %>%
  filter(!subid %in% drop) %>%
  group_by(subage) %>%
  summarise(n = length(unique(subid)))

```

# Visualizing the data

```{r}
p1 <- data %>%
      filter(phase == "test")%>% # only test trials
  group_by(subage, subid) %>%
  summarise(correct = mean(correct_target1)) 

p2 <- p1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = p1, aes(x = subage, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = subage, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="",y="Proportion Correct Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Age")
```

# Power analysis
``` {r power analysis}
power <- data %>%
  filter(phase == 'test') %>%
  group_by(subid) %>%
  summarise(correct = mean(correct_target1))

t.test(power$correct, mu = 1/3)

d <- cohensD(power$correct, mu = 1/3)

pwr.t.test(d = d, sig.level = 0.05, power = .8, type = c("one.sample"))
```

# Bayesian Power analysis

```{r}
N           <- 1000  # Number of MC reps
n           <- 20  # Sample size
sigma       <- 0.3    # Error standard devation

true_mu     <- (0.5785714-1/3)	  # True value of mu

pri.mn.anal <- 0    # Prior for mu
pri.sd.anal <- Inf


 L <- rep(0,N)
 U <- rep(0,N)

 set.seed(0820)

 for(rep in 1:N){

  #Generate data:
    Y  <- rnorm(n,true_mu,sigma)

   #Compute posterior 95% interval:
    post.var <- 1/(n/sigma^2+1/pri.sd.anal^2)
    post.mn  <- post.var*(pri.mn.anal/pri.sd.anal^2+sum(Y)/sigma^2)
    L[rep]   <- post.mn-1.96*sqrt(post.var)
    U[rep]   <- post.mn+1.96*sqrt(post.var)
 }
 
 
plot(NA,xlim=c(-1,1),ylim=c(1,N),xlab="95% interval",ylab="Replication")
abline(v=0)

for(rep in 1:N){
    reject <- L[rep]>0 | U[rep]<0
    lines(c(L[rep],U[rep]),c(rep,rep),col=ifelse(reject>0,2,1))
}


 mean(L>0 | U<0)
```