---
title: "DisCon Children Speaker Change"
output: html_document
  code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(jsonlite)
library(tidyr)
library(stringr)
library(dplyr)
library(ggthemes)
library(langcog)
library(readxl)
library(knitr)

library(lsr)
library(pwr)

library(coda)
library(reshape2)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

```

```{r data pre-processing, include = F}

#files <- dir("../../kids_simple_4cat/")
files <- dir("../../kids_raw_data/speaker_change/")

raw_data <- data_frame()
for (f in files) {
#  jf <- paste("../../kids_simple_4cat/",f,sep="")
  jf <- paste("../../kids_raw_data/speaker_change/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  date <- str_sub(jf,58,str_length(jf)-11)
  id <- as_data_frame(jd$data$data)%>% mutate(test_date = date)
  raw_data <- bind_rows(raw_data, id)
}

raw_data <- raw_data %>%
   mutate(subid = str_replace(subid, "_d600","_dsc"),
          subid = ifelse(subid == "190915_1_dsc", "190918_1_dsc", subid),
          subid = ifelse(subid == "190929_2_dsc", "190920_2_dsc", subid))

unique(raw_data$subid)

# linking the data to the demographics spreadsheet
# always check if subjects get "lost" due do differetn subids
log <- read_excel("../../DisCon-subject_log.xlsx", 1)%>%
  filter(Condition == "dsc")%>%
  mutate(dob = as.numeric(dob),
         dob = as.Date(dob,origin = "1899-12-30"))%>%
  select(subid,experimenter,keep_drop,sex,dob)


raw_data%>%
  filter(experiment =="distribution_kids_simple_speakerchange")%>%
  group_by(subid)%>%
  summarise(n())%>%
  filter(!(subid %in% unique(log$subid)))

#unique(log$subid)

data <- left_join(raw_data,log, by = "subid")%>%
  filter(keep_drop == "keep")%>%
  mutate(distribution = as.character(distribution),
         age_num = lubridate::time_length(difftime(test_date,dob), "years"),
         check_age = ifelse(substr(age_num,1,1) == subage, T, F), 
         distribution = ifelse(distribution == "c(6, 0, 0)", "6-0-0","1-0-0"))%>%
  select(-dob, check_age,-keep_drop,-experimenter,-test_date)

#unique(data$subid)

#write.csv(data, file="../data/kids_speaker_change_data.csv")

##data <- read_csv(file="../data/kids_speaker_change_data.csv")
```


```{r sanity checks}
# filtering out subjects that perform poorly on training trials
data %>%
  filter(phase == 'training') %>%
  group_by(subid) %>%
  summarise(correct = mean(correct_item))

drop <- data %>%
  filter(phase == 'training') %>%
  group_by(subid) %>%
  summarise(correct = mean(correct_item)) %>%
  filter(correct < 0.83) %>%
  pull(subid)

data <- data %>%
  filter(!subid %in% drop,
         subage != "2")
```

```{r}
#clean data file for repo
data_ex3 <- data %>%
  filter(subage != "2",
         phase == "test")%>%
  mutate(correct = ifelse(correct_target1 == "1", 1, 0),
         condition = ifelse(speakerChange == "same", "same_speaker", "different_speaker"),
         target_category = target1, 
         picked_category = pickCat,
         experiment = "speaker_change", 
         id = paste0("part_",as.numeric(as.factor(subid))),
         id = paste(id, experiment, sep = "_"),
         speaker = ifelse(speakerChange == "change", alternativeAgent, agent),
         age_group = subage)%>%
  select(id, age_group,age_num,sex,experiment,trial,condition, speaker, target_category, picked_category,correct)


write_csv(data_ex3, path="../data/data_ex3.csv")
```

# Participants

```{r}
data %>%
  group_by(subage)%>%
  summarise(n = length(unique(subid)))%>%
  knitr::kable(digits = 2)
```

# Proportion correct choice in training trials

```{r}
pt1 <- data %>%
  filter(phase == 'training')%>%
  group_by(subage, subid) %>%
  summarise(correct = mean(correct_item)) 

pt2 <- pt1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = pt1, aes(x = subage, y = correct, col = subage, alpha = .2),width = .1,height = .0)+
  geom_pointrange(data = pt2, aes(x = subage, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="",y="Proportion correct in training")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+
  scale_color_solarized()

```

# Proportion correct choice in test trials across age bins

```{r proportion of choices}
p1 <- data %>%
  filter(phase == 'test')%>%
  group_by(age_num,speakerChange,subid) %>%
  summarise(correct = mean(correct_target1)) 

p2 <- p1 %>%
  group_by(speakerChange) %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_point(data = p1, aes(x = speakerChange, y = correct, col = speakerChange), alpha = .2 , position = position_jitterdodge(dodge.width = .5, jitter.width = .1))+
  geom_pointrange(data = p2, aes(x = speakerChange, y = mean,  ymin = ci_lower, ymax = ci_upper, col = speakerChange),size = .8, position = position_dodge(width = .5))+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="",y="Proportion correct")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+
  scale_color_ptol()
```

```{r proportion of choices}
p3 <- data %>%
  filter(phase == 'test')%>%
  group_by(subage, speakerChange,subid) %>%
  summarise(correct = mean(correct_target1)) 

p4 <- p3 %>%
  group_by(subage,speakerChange) %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_point(data = p3, aes(x = subage, y = correct, col = speakerChange), alpha = .2 , position = position_jitterdodge(dodge.width = .5, jitter.width = .1))+
  geom_pointrange(data = p4, aes(x = subage, y = mean,  ymin = ci_lower, ymax = ci_upper, col = speakerChange),size = .8, position = position_dodge(width = .5))+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="",y="Proportion correct")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+
  scale_color_ptol()
```

```{r}
library(BayesFactor)

data %>%
  filter(phase != "training") %>%
  group_by(subage,subid) %>%
  summarise(correct = mean(correct_target1)) %>%
  summarise(correct = list(correct)) %>%
  group_by(subage)%>%
  mutate(mean= mean(unlist(correct)),
         bf = extractBF(ttestBF(unlist(correct), mu = 1/3))$bf) %>%
  select(subage,mean,bf)


plot_post <- data %>%
  filter(phase != "training") %>%
  group_by(subage,subid) %>%
  summarise(correct = mean(correct_target1))%>%
  summarise(correct = list(correct)) %>%
  group_by(subage) %>%
  mutate(posterior = list((ttestBF(unlist(correct), mu = 1/3, posterior = T, iterations = 1000)[,"mu"])))%>%
  select(-correct)

plot_dens_ci <- plot_post %>%
  summarise(mode = estimate_mode(unlist(posterior)),
            lci = hdi_lower(unlist(posterior)),
            uci = hdi_upper(unlist(posterior)))
```


# Proportion correct choice by age continous

```{r}
p5 <- data %>%
  filter(phase == 'test')%>%
  group_by(speakerChange,age_num, subid) %>%
  summarise(correct = mean(correct_target1)) 

ggplot(data = p5, aes(x = age_num, y = correct, col = speakerChange,fill = speakerChange)) +
  geom_jitter(width = .01, height = .0, alpha = .5)+
  geom_smooth(method = "glm",  span = 1, se = T,  alpha = .5, size = 1, alpha = .5 )+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="Age",y="Proportion correct")+
  theme_few() +
  ylim(-0.05,1.05)+
  xlim(3,5)+
  guides(alpha = F)+
  scale_color_ptol()+
  scale_fill_ptol()
```

# Model 
```{r, include = F}
library(brms)

model_data <- data%>%
  filter(phase != "training")%>%
  mutate(age_num = scale(age_num),
         item = ifelse(speakerChange == "change", alternativeAgent, agent))

#   model

kbm1 <- brm(correct_target1 ~ age_num * speakerChange +
                      (speakerChange| subid) + (age_num * speakerChange | item),
                    data = model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 5000)

summary(kbm1)


kbm1_1 <- brm(correct_target1 ~ age_num * speakerChange +
                      (speakerChange| subid),
                    data = model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 5000)

summary(kbm1_1)

model_weights(kbm1, kbm1_1, weights = "waic")

```

```{r}
bayesplot::mcmc_areas(as.array(kbm1), pars = c("b_Intercept", "b_age_num", "b_speakerChangesame", "b_age_num:speakerChangesame"), prob = 0.95)+
  geom_vline(xintercept = 0, lty = 2, col = "black")+
  theme_few()
```


```{r, include = F}
kbm2 <- brm(correct_target1 ~ age_num + speakerChange +
                      (speakerChange| subid) + (age_num * speakerChange | item),
                    data = model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 5000)

summary(kbm2)


kbm2_2 <- brm(correct_target1 ~ age_num + speakerChange +
                      (speakerChange| subid),
                    data = model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 20000)

summary(kbm2_2)
```

```{r}
bayesplot::mcmc_areas(as.array(kbm2), pars = c("b_Intercept", "b_age_num", "b_speakerChangesame"), prob = 0.95)+
  geom_vline(xintercept = 0, lty = 2, col = "black")+
  theme_few()
```

```{r, include = F}
kbm3 <- brm(correct_target1 ~ age_num +
                      (speakerChange| subid) + (age_num * speakerChange | item),
                    data = model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 5000)

summary(kbm3)


kbm3_3 <- brm(correct_target1 ~ age_num +
                      (speakerChange| subid),
                    data = model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 20000)

summary(kbm3_3)
```

## Model comparison

```{r}
child_waic <- brms::waic(kbm1, kbm2, kbm3, compare = F)

child_weights <- model_weights(kbm1, kbm2,kbm3, weights = "waic")

# Bayes Factors (slightly variable)
bf_full_null_1 <- bayes_factor(kbm1, kbm3, log = FALSE, maxiter = 5000)

bf_full_null_2 <- bayes_factor(kbm1, kbm2, log = FALSE, maxiter = 5000)

bf_full_null_3 <- bayes_factor(kbm2, kbm3, log = FALSE, maxiter = 5000)
```


```{r}
data_frame(
  model = c("model_w_int","model_w_condition","null_model"),
  WAIC = c(child_waic$loo$kbm1$estimates[3,1],child_waic$loo$kbm2$estimates[3,1],child_waic$loo$kbm3$estimates[3,1]),
  SE = c(child_waic$loo$kbm1$estimates[3,2],child_waic$loo$kbm2$estimates[3,2],child_waic$loo$kbm3$estimates[3,2]),
  weight = c(child_weights[1],child_weights[2],child_weights[3]),
  BF_vs_null = c(round(bf_full_null_1$bf,2),round(bf_full_null_3$bf,2),"-"))%>%
  kable(digits = 2)
```

# Check category, position and trial

## category effects
```{r proportion of choices}
cat_plot <- data %>%
  filter(phase == 'test')%>%
  group_by(target1,subid) %>%
  summarise(correct = mean(correct_target1)) 

cat_plot_mean <- cat_plot %>%
  group_by(target1) %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = cat_plot, aes(x = target1, y = correct,  alpha = .2, col = target1),width = .2,height = .01)+
  geom_pointrange(data = cat_plot_mean, aes(x = target1, y = mean,  ymin = ci_lower, ymax = ci_upper, col = target1),size = .8)+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="",y="Proportion correct")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F, col = F)+
  scale_color_solarized()
```

## position effects
```{r }
pos_plot <- data %>%
  filter(phase == 'test')%>%
  group_by(pickPos,subid) %>%
  summarise(n = n())%>%
  group_by(pickPos)%>%
  multi_boot_standard(col = "n")

ggplot() +
  geom_pointrange(data = pos_plot, aes(x = pickPos, y = mean,  ymin = ci_lower, ymax = ci_upper),size = .8)+
   labs(x="Item position",y="Mean item in this position chosen at test")+
  theme_few() +
  ylim(0,4)+
  guides(alpha = F)+
  scale_color_solarized()
```

## trial effects
```{r proportion of choices}
trial_plot <- data %>%
  filter(phase == 'test')

ggplot(data = trial_plot, aes(x = trial, y = correct_target1)) +
  geom_jitter(alpha = .2,width = .2,height = .01)+
  geom_smooth(method = "loess",  se = T, size = 1, col = "darkred", fill = "darkgreen", alpha = .5 )+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="",y="Proportion correct")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+
  scale_color_solarized()
```

# one sample wilcoxon
```{r}

# Based on: http://ipg.idsia.ch/preprints/benavoli2014a.pdf
source("../scripts/isignrank.test.R")

rank_data <- data %>%
  filter(phase == 'test')%>%
  group_by(speakerChange,subage,subid) %>%
  summarise(correct = mean(correct_target1)) %>%
  mutate(chance = rep(1/3,length(correct)))

isignrank.test(rank_data$chance,rank_data$correct,"two.sided")

# Based on : https://arxiv.org/pdf/1712.06941.pdf
source("../scripts/signRankSampler.R")

rank_test <- signRankGibbsSampler(rank_data$correct,rank_data$chance)

rank_test_plot <- data.frame(rank_test)

ggplot(rank_test_plot, aes(plogis(deltaSamples))) +
  geom_density(alpha = .5)+
  xlim(0,1)
```

